import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Login from '../components/Login'
import Sidebar from '../components/Sidebar'
import { getSession, useSession } from 'next-auth/react'
import Widgets from '../components/Widgets'
import FeedContainer from '../components/FeedContainer'

export default function Home() {
  const { data: session } = useSession()
  if(!session) return <Login/>
  
  return (
    <div className='h-screen bg-gray-100 overflow-hidden'>
      <Head>
        <title>Letbook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className='flex '>
        {/**<SideBar/> */}
        <Sidebar/>
        {/**<Feed/> */}
        <FeedContainer/>
        {/**<Widgets/> */}
        <Widgets/>
      </main>
    </div>
    )
}


export async function getServerSideProps(context) {
  return {
    props: {
      session: await getSession(context),
    },
  }
}