import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Login from '../components/Login'
import Sidebar from '../components/Sidebar'
import { getSession, useSession } from 'next-auth/react'
import Widgets from '../components/Widgets'
import FeedContainer from '../components/FeedContainer'
import { collection, orderBy, query, getDocs, getDoc } from 'firebase/firestore'
import { db } from '../firebase'

export default function Home({ posts}) {
  const { data: session } = useSession()
  if(!session) return <Login/>
  
  return (
    <div className='h-screen bg-gray-100 overflow-hidden'>
      <Head>
        <title>Letbook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className='flex '>
        {/**<SideBar/> */}
        <Sidebar/>
        {/**<Feed/> */}
        <FeedContainer posts={posts}/>
        {/**<Widgets/> */}
        <Widgets/>
      </main>
    </div>
    )
}


export async function getServerSideProps(context) {

  const q =  query(collection(db, 'posts/'), orderBy('timestamp', 'desc'))
  const posts = await getDocs(q)
  
  const documentos = posts.docs.map((post) => ({
    id: post.id,
    ...post.data(),
    timestamp:null,
  }))

  return {
    props: {
      session: await getSession(context),
      posts: documentos,
    },
  }
}